update

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -1,7 +1,31 @@
 #!/bin/zsh
 
-if [[ ! -d $HOME/.oh-my-zsh ]]; then
-  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
+export ZSH=$HOME/.oh-my-zsh
+
+if [[ ! -d $HOME/.oh-my-zsh ]] ; then
+	umask g-w,o-w
+  REPO=${REPO:-ohmyzsh/ohmyzsh}
+  REMOTE=${REMOTE:-https://github.com/${REPO}.git}
+  BRANCH=${BRANCH:-master}
+
+	echo "${BLUE}Cloning Oh My Zsh...${RESET}"
+
+	if [ "$OSTYPE" = cygwin ] && git --version | grep -q msysgit; then
+		error "Windows/MSYS Git is not supported on Cygwin"
+		error "Make sure the Cygwin git package is installed and is first on the \$PATH"
+		exit 1
+	fi
+
+	git clone -c core.eol=lf -c core.autocrlf=false \
+		-c fsck.zeroPaddedFilemode=ignore \
+		-c fetch.fsck.zeroPaddedFilemode=ignore \
+		-c receive.fsck.zeroPaddedFilemode=ignore \
+		--depth=1 --branch "$BRANCH" "$REMOTE" "$ZSH" || {
+		error "git clone of oh-my-zsh repo failed"
+		exit 1
+	}
+
+	echo
 fi
 
 ### Added by Zinit's installer
@@ -17,7 +41,9 @@ autoload -Uz _zinit
 (( ${+_comps} )) && _comps[zinit]=_zinit
 ### End of Zinit installer's chunk
 
-export ZSH=$HOME/.oh-my-zsh
+
+. "$HOME/.oh-my-zsh/oh-my-zsh.sh"
+
 # export DEFAULT_USER="tMinamiii"
 set bell-style none
 skip_global_compinit=1
@@ -26,16 +52,12 @@ ZSH_THEME=""
 
 plugins=(
   docker
-  docker-compose
   git
   ripgrep
-  tig
-  tmux
 )
 
-. "$HOME/.oh-my-zsh/oh-my-zsh.sh"
-
 # User configuration
+[ "$TMUX" != "" ] && export TERM="screen-256color"
 export MANPATH="/usr/local/man:$MANPATH"
 
 export LC_CTYPE=en_US.UTF-8
@@ -58,10 +80,6 @@ export LSCOLORS=gxfxxxxxcxxxxxxxxxgxgx
 export LS_COLORS='di=01;36:ln=01;35:ex=01;32'
 export GOOGLE_APPLICATION_CREDENTIALS="$HOME/.gcp.json"
 
-export ENHANCD_COMMAND=cdd
-zstyle ':completion:*' list-colors 'di=36' 'ln=35' 'ex=32'
-
-[ "$TMUX" != "" ] && export TERM="screen-256color"
 
 if uname -a | grep -sq "Ubuntu"; then
   # LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
@@ -77,6 +95,9 @@ elif uname -a | grep -sq "microsoft"; then
 fi
 
 export PATH="$HOME/.anyenv/bin:$HOME/.local/bin:$HOME/.cargo/bin:$HOME/bin:$GOBIN:$PATH"
+export ENHANCD_COMMAND=cdd
+zstyle ':completion:*' list-colors 'di=36' 'ln=35' 'ex=32'
+
 
 alias build-vim='make clean && make distclean  && ./configure  --prefix=/usr/local/ --with-features=huge --enable-multibyte --enable-gpm --enable-cscope --enable-perlinterp --enable-python3interp --with-python3-command=$(echo $HOME)/.anyenv/envs/pyenv/shims/python --enable-rubyinterp --enable-luainterp --enable-acl --enable-fontset --enable-xim --enable-terminal --enable-fail-if-missing --with-luajit --with-x && make && sudo make install'
 alias build-nvim='sudo rm -rf .deps build && sudo make clean && sudo make CMAKE_BUILD_TYPE=Release && sudo make CMAKE_INSTALL_PREFIX=/usr/local install'
@@ -99,64 +120,57 @@ alias pi3='ssh ubuntu@172.16.27.12'
 # ghq
 alias github='gh-open $(repos)'
 
-function nuxt_setup() {
-  echo -n "ok?(y/N): "
-  if read -q; then
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-nuxt/master/package.json
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-nuxt/master/.eslintrc.js
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-nuxt/master/.eslintignore.js
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-nuxt/master/tsconfig.js
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-nuxt/master/nuxt.config.ts
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-nuxt/master/jest.config.js
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-nuxt/master/index.d.ts
-  else
-    echo abort
-  fi
-}
+# function nuxt_setup() {
+#   echo -n "ok?(y/N): "
+#   if read -q; then
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-nuxt/master/package.json
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-nuxt/master/.eslintrc.js
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-nuxt/master/.eslintignore.js
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-nuxt/master/tsconfig.js
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-nuxt/master/nuxt.config.ts
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-nuxt/master/jest.config.js
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-nuxt/master/index.d.ts
+#   else
+#     echo abort
+#   fi
+# }
+#
+# function react_setup() {
+#   echo -n "ok?(y/N): "
+#   if read -q; then
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-react/master/.eslintrc.js
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-react/master/.stylelintrc.js
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-react/master/package.json
+#   else
+#     echo abort
+#   fi
+# }
+#
+# function python_setup () {
+#   echo -n "ok?(y/N): "
+#   if read -q; then
+#     if [ ! -e "/.vscode" ]; then
+#       mkdir .vscode
+#       curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/.vscode/settings.json -o .vscode/settings.json
+#     fi
+#     # curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/.env.workspace
+#     # curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/.envrc
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/.flake8
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/.gitignore
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/.isort.cfg
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/.mypy.ini
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/.pre-commit-config.yaml
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/requirements.txt
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/editorconfig
+#     curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/pyproject.toml
+#     python -m venv .venv
+#     poetry config --local virtualenvs.in-project true
+#     poetry add -D $(cat requirements.txt)
+#   else
+#     echo abort
+#   fi
+# }
 
-function react_setup() {
-  echo -n "ok?(y/N): "
-  if read -q; then
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-react/master/.eslintrc.js
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-react/master/.stylelintrc.js
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/ts-react/master/package.json
-  else
-    echo abort
-  fi
-}
-
-function python_setup () {
-  echo -n "ok?(y/N): "
-  if read -q; then
-    if [ ! -e "/.vscode" ]; then
-      mkdir .vscode
-      curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/.vscode/settings.json -o .vscode/settings.json
-    fi
-    # curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/.env.workspace
-    # curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/.envrc
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/.flake8
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/.gitignore
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/.isort.cfg
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/.mypy.ini
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/.pre-commit-config.yaml
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/requirements.txt
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/editorconfig
-    curl -L -O https://raw.githubusercontent.com/tMinamiii/python-template/master/pyproject.toml
-    python -m venv .venv
-    poetry config --local virtualenvs.in-project true
-    poetry add -D $(cat requirements.txt)
-  else
-    echo abort
-  fi
-}
-
-function pip3_upgrade () {
-  pip3 install --upgrade pip && pip3 list --outdated --format columns | awk 'NR>2{print $1}' | xargs pip3 install --upgrade
-}
-
-function pip2_upgrade () {
-  pip2 install --upgrade pip && pip2 list --outdated --format columns | awk 'NR>2{print $1}' | xargs pip2 install --upgrade
-}
 
 function ghq-fzf() {
   local src=$(ghq list | fzf )
@@ -173,18 +187,28 @@ function npm_freeze() {
   npm list -g --depth=0 | tail +2 | awk '{ print $2 }' | sed -e 's/\@[0-9].*$//g' | tr '\n' ' '
 }
 
-[ -f ~/.anyenv/bin/anyenv ] && eval "$(anyenv init - --no-rehash)"
 [ -f "$(which hub)" ] && eval "$(hub alias -s)"
 [ -f "$(which direnv)" ] && eval "$(direnv hook zsh)"
 [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
 
+### anyenv ###
+# [ -f ~/.anyenv/bin/anyenv ] && eval "$(anyenv init - --no-rehash)"
+XDG_CACHE_HOME="$HOME/.cache"
+function cache-anyenv() {
+    [[ -d $XDG_CACHE_HOME/anyenv ]] || mkdir -p $XDG_CACHE_HOME/anyenv
+    anyenv init - > $XDG_CACHE_HOME/anyenv/init.zsh
+}
+
+if [[ -x $ANYENV_ROOT/bin/anyenv ]]; then
+    [[ -f $XDG_CACHE_HOME/anyenv/init.zsh ]] || cache-anyenv
+
+    source $XDG_CACHE_HOME/anyenv/init.zsh
+fi
+
 zinit ice pick"async.zsh" src"pure.zsh"
 zinit light sindresorhus/pure
-# zinit light denysdovhan/spaceship-prompt
 zinit light zsh-users/zsh-autosuggestions
 zinit light b4b4r07/enhancd
 bindkey '^[' autosuggest-accept
 
-if [ ~/.zshrc -nt ~/.zshrc.zwc ]; then
-  zcompile ~/.zshrc
-fi
+[ ~/.zshrc -nt ~/.zshrc.zwc ] && zcompile ~/.zshrc
